Repository eclipse-edc/.github, pull requests merged in 2023-07, with the labels that each got.

#3 fix(profile): update link to developer documentation
  profile/README.md
Labels: bug

#4 fix(profile): update broken links
  profile/README.md
Labels: bug

#50 feat: add basic workflows from connector repo
  .github/actions/bump-version/action.yml
  .github/actions/run-tests/action.yml
  .github/actions/setup-build/action.yml
  .github/release.yaml
  .github/workflows/add-to-project.yml
  .github/workflows/bump-version.yaml
  .github/workflows/close-inactive-issues.yml
  .github/workflows/discord-webhook.yml
  .github/workflows/first-interaction.yml
Labels: enhancement

#52 chore: fix links and add license
  .github/workflows/release-component.yml
  LICENSE
  contributing/adoption.md
  contributing/coding-principles.md
  contributing/pr_etiquette.md
  contributing/styleguide.md
  docs/decision-records/2022-02-10-code-coverage/README.md
  docs/decision-records/2022-02-10-code-coverage/jacoco_github_action.md
  docs/decision-records/2022-02-10-code-coverage/sonarqube.md
  docs/decision-records/2022-02-11-codeql/README.md
  docs/decision-records/2022-08-11-versioning_and_artifacts/README.md
  docs/developer/autodoc.md
  docs/developer/logging.md
  docs/developer/testing.md
Labels: documentation, enhancement

#53 feat(ci): add DEPENDENCIES check workflow
  .github/workflows/dependency-check.yml
Labels: documentation

#54 feat: add reusable workflows
  .github/workflows/discord-webhook.yml
  .github/workflows/first-interaction.yml
  .github/workflows/scan-pull-request.yml
  .github/workflows/stale-bot.yml
  contributing/pr_etiquette.md
Labels: enhancement

#55 refactor: update documentation from connector repo
  CONTRIBUTING.md
  contributing/styleguide.md
  docs/developer/autodoc.md
  docs/developer/releases.md
  docs/developer/testing.md
  docs/developer/version-catalogs.md
  docs/legal/generateThirdPartyReport.sh
Labels: documentation

#57 fix: print dependencies file on failure
  .github/workflows/dependency-check.yml
Labels: bug
